name: Build iOS App and Generate IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g react-native-cli

    - name: Build iOS App - Debug
      run: |
        cd ios
        pod install
        cd ..
        react-native run-ios --configuration=Debug --device

    - name: Generate IPA - Debug
      run: |
        cd ios
        xcodebuild -workspace ReactNativeCI.xcworkspace -scheme YourScheme -configuration Debug -archivePath build/YourApp-debug.xcarchive archive
        xcodebuild -exportArchive -archivePath build/YourApp-debug.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
      env:
        APP_NAME: YourAppName

    - name: Archive IPA - Debug
      uses: actions/upload-artifact@v2
      with:
        name: ios-ipa-debug
        path: ios/build/*.ipa

    - name: Build iOS App - Release
      run: |
        cd ios
        pod install
        cd ..
        react-native run-ios --configuration=Release --device

    - name: Generate IPA - Release
      run: |
        cd ios
        xcodebuild -workspace ReactNativeCI.xcworkspace -scheme YourScheme -configuration Release -archivePath build/YourApp-release.xcarchive archive
        xcodebuild -exportArchive -archivePath build/YourApp-release.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
      env:
        APP_NAME: YourAppName

    - name: Archive IPA - Release
      uses: actions/upload-artifact@v2
      with:
        name: ios-ipa-release
        path: ios/build/*.ipa
