name: Build iOS App and Generate IPA

on:
  push:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g react-native-cli

    - name: Build iOS App
      run: |
        cd ios
        pod install
        cd ..
        react-native run-ios --configuration=release --device

    - name: Generate IPA
      run: |
        cd ios
        xcodebuild -workspace ReactNativeCI.xcworkspace -scheme ReactNativeCI -configuration Release -archivePath build/ReactNativeCI.xcarchive archive
        xcodebuild -exportArchive -archivePath build/ReactNativeCI.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
      env:
        APP_NAME: ReactNativeCI

    - name: Archive IPA
      uses: actions/upload-artifact@v2
      with:
        name: ios-ipa
        path: ios/build/*.ipa
